name: Lint and Auto-Fix for Python and JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black to Auto-Fix Python Code
      run: |
        black . --line-length 88
        git config --global user.email "uhaz.88@gmail.com"
        git config --global user.name "UttaranHazarika"
        git add .
        git commit -m "Auto-fix Python code with Black" || echo "No changes to commit"

    # Step 3: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install JavaScript dependencies
      run: npm install eslint prettier --save-dev

    - name: Run ESLint and Prettier to Auto-Fix JavaScript Code
      run: |
        npx eslint '**/*.js' --fix
        npx prettier '**/*.{js,json,css,html}' --write
        git add .
        git commit -m "Auto-fix JavaScript code with ESLint and Prettier" || echo "No changes to commit"

    # Step 4: Push changes back to the repository
    - name: Push Changes
      run: git push || echo "No changes to push"
