name: 'Lint Code with Auto-Fix'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint and Auto-Fix Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run Linter and Auto-Fix
      run: |
        # Auto-fix Python code with Black
        black . --line-length 88
        # Lint Python code with Flake8
        find . -name "*.py" -exec flake8 {} +
        echo "Linted and formatted all Python files successfully"

    - name: Commit and Push Changes
      run: |
        git config --global user.email "uhaz.88@gmail.com"
        git config --global user.name "UttaranHazarika"
        git add .
        git commit -m "Auto-fix Python code with Black" || echo "No changes to commit"
        git push || echo "No changes to push"

  lint_js:
    name: Lint and Auto-Fix JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install ESLint
      run: npm install eslint --global

    - name: Run Linter and Auto-Fix
      run: |
        # Auto-fix JavaScript code with ESLint
        eslint "**/*.js" --fix
        echo "Linted and formatted all JavaScript files successfully"

    - name: Commit and Push Changes
      run: |
        git config --global user.email "uhaz.88@gmail.com"
        git config --global user.name "UttaranHazarika"
        git add .
        git commit -m "Auto-fix JavaScript code with ESLint" || echo "No changes to commit"
        git push || echo "No changes to push"
